name: 不具合報告
description: 不具合を報告する
title: "[BUG]: "
labels: ["bug"]
assignees:
  - ot07
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 概要
      description: 発生した不具合の概要を記載する。不具合の内容が分かる動画やスクリーンショットがあれば添付する。
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待する動作
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      value: |
        1.
        2.
        3.
    validations:
      required: false
  - type: textarea
    id: cause
    attributes:
      label: 原因
      description: 不具合の原因と思われる箇所が分かれば記載する。
    validations:
      required: false
  - type: textarea
    id: how-to-fix
    attributes:
      label: 修正方法
      description: 不具合の修正方法が分かれば記載する。
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: 補足
    validations:
      required: false
