name: 不具合報告
description: 不具合を報告する
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ot07
body:
  - type: textarea
    id: what-happened
    attributes:
      label: 概要
      description: 発生した不具合の概要を記載する。不具合の内容が分かる動画やスクリーンショットがあれば添付する。
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待する動作
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順（任意）
      value: |
        1.
        2.
        3.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: 補足（任意）
    validations:
      required: false
